
package uk.co.o2.soa.useraccountsservice_1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import uk.co.o2.soa.useraccountsdata_1.CreateOrUpdateUser;
import uk.co.o2.soa.useraccountsdata_1.CreateOrUpdateUserResponse;
import uk.co.o2.soa.useraccountsdata_1.GetUserDetails;
import uk.co.o2.soa.useraccountsdata_1.GetUserDetailsResponse;
import uk.co.o2.soa.useraccountsdata_1.GetUserNameSuggestion;
import uk.co.o2.soa.useraccountsdata_1.GetUserNameSuggestionResponse;
import uk.co.o2.soa.useraccountsdata_1.Search;
import uk.co.o2.soa.useraccountsdata_1.SearchOnlineAccounts1;
import uk.co.o2.soa.useraccountsdata_1.SearchOnlineAccounts1Response;
import uk.co.o2.soa.useraccountsdata_1.SearchResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserAccountsPortType", targetNamespace = "http://soa.o2.co.uk/useraccountsservice_1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    uk.co.o2.soa.coredata_1.ObjectFactory.class,
    uk.co.o2.soa.pscommonregistrationdata_1.ObjectFactory.class,
    uk.co.o2.soa.pscommonregistrationdata_2.ObjectFactory.class,
    uk.co.o2.soa.useraccountsdata_1.ObjectFactory.class
})
public interface UserAccountsPortType {


    /**
     * 
     * @param getUserDetails
     * @return
     *     returns uk.co.o2.soa.useraccountsdata_1.GetUserDetailsResponse
     * @throws GetUserDetailsFault
     */
    @WebMethod
    @WebResult(name = "getUserDetailsResponse", targetNamespace = "http://soa.o2.co.uk/useraccountsdata_1", partName = "getUserDetailsResponse")
    public GetUserDetailsResponse getUserDetails(
        @WebParam(name = "getUserDetails", targetNamespace = "http://soa.o2.co.uk/useraccountsdata_1", partName = "getUserDetails")
        GetUserDetails getUserDetails)
        throws GetUserDetailsFault
    ;

    /**
     * 
     * @param search
     * @return
     *     returns uk.co.o2.soa.useraccountsdata_1.SearchResponse
     * @throws SearchFault
     */
    @WebMethod
    @WebResult(name = "searchResponse", targetNamespace = "http://soa.o2.co.uk/useraccountsdata_1", partName = "searchResponse")
    public SearchResponse search(
        @WebParam(name = "search", targetNamespace = "http://soa.o2.co.uk/useraccountsdata_1", partName = "search")
        Search search)
        throws SearchFault
    ;

    /**
     * 
     * @param createOrUpdateUser
     * @return
     *     returns uk.co.o2.soa.useraccountsdata_1.CreateOrUpdateUserResponse
     * @throws CreateOrUpdateUserFault
     */
    @WebMethod
    @WebResult(name = "createOrUpdateUserResponse", targetNamespace = "http://soa.o2.co.uk/useraccountsdata_1", partName = "createOrUpdateUserResponse")
    public CreateOrUpdateUserResponse createOrUpdateUser(
        @WebParam(name = "createOrUpdateUser", targetNamespace = "http://soa.o2.co.uk/useraccountsdata_1", partName = "createOrUpdateUser")
        CreateOrUpdateUser createOrUpdateUser)
        throws CreateOrUpdateUserFault
    ;

    /**
     * 
     * @param getUserNameSuggestion
     * @return
     *     returns uk.co.o2.soa.useraccountsdata_1.GetUserNameSuggestionResponse
     * @throws GetUserNameSuggestionFault
     */
    @WebMethod
    @WebResult(name = "getUserNameSuggestionResponse", targetNamespace = "http://soa.o2.co.uk/useraccountsdata_1", partName = "getUserNameSuggestionResponse")
    public GetUserNameSuggestionResponse getUserNameSuggestion(
        @WebParam(name = "getUserNameSuggestion", targetNamespace = "http://soa.o2.co.uk/useraccountsdata_1", partName = "getUserNameSuggestion")
        GetUserNameSuggestion getUserNameSuggestion)
        throws GetUserNameSuggestionFault
    ;

    /**
     * 
     * @param searchOnlineAccounts1
     * @return
     *     returns uk.co.o2.soa.useraccountsdata_1.SearchOnlineAccounts1Response
     * @throws SearchOnlineAccounts1Fault
     */
    @WebMethod(operationName = "searchOnlineAccounts_1")
    @WebResult(name = "searchOnlineAccounts_1Response", targetNamespace = "http://soa.o2.co.uk/useraccountsdata_1", partName = "searchOnlineAccounts_1Response")
    public SearchOnlineAccounts1Response searchOnlineAccounts1(
        @WebParam(name = "searchOnlineAccounts_1", targetNamespace = "http://soa.o2.co.uk/useraccountsdata_1", partName = "searchOnlineAccounts_1")
        SearchOnlineAccounts1 searchOnlineAccounts1)
        throws SearchOnlineAccounts1Fault
    ;

}
